# Generated by Django 4.2.2 on 2023-06-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(help_text='pul miqdori')),
                ('comment', models.CharField(help_text='nima uchun sarflandi', max_length=500)),
                ('person', models.CharField(blank=True, help_text='kim sarfladi', max_length=200, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='mahsulot nomi', max_length=100)),
                ('buy_price', models.FloatField(help_text='kelish narxi')),
                ('sell_price', models.FloatField(help_text='sotish narxi')),
                ('miqdori', models.IntegerField()),
                ('izoh', models.CharField(blank=True, help_text='litri, brandi....', max_length=500, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='mahsulot filteri', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oluvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='mashina nomi', max_length=100)),
                ('car_number', models.CharField(help_text='mashina raqami', max_length=20)),
                ('total_cost', models.FloatField(help_text='umumiy narx')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cost', models.FloatField()),
                ('oluvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savdolar', to='base.mahsulot')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mahsulot_filter'),
        ),
    ]
