# Generated by Django 4.2.2 on 2023-06-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='comment',
            field=models.CharField(help_text='nima uchun sarflandi', max_length=500, verbose_name="Nima uchun sarflandi'"),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='date',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='money',
            field=models.FloatField(help_text='pul miqdori', verbose_name='Pul miqdori'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='person',
            field=models.CharField(blank=True, help_text='kim sarfladi', max_length=200, null=True, verbose_name='Kim sarfladi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='buy_price',
            field=models.FloatField(help_text='kelish narxi', verbose_name='Kelish narxi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mahsulot_filter', verbose_name='Filteri'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='izoh',
            field=models.TextField(blank=True, help_text='litri, brendi....', max_length=500, null=True, verbose_name='Litri, brendi....'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='miqdori',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='product_name',
            field=models.CharField(help_text='mahsulot nomi', max_length=100, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='sell_price',
            field=models.FloatField(help_text='sotish narxi', verbose_name='Sotish narxi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='time',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='mahsulot_filter',
            name='name',
            field=models.CharField(help_text='mahsulot filteri', max_length=100, verbose_name='Mahsulot filteri'),
        ),
        migrations.AlterField(
            model_name='oluvchi',
            name='car_number',
            field=models.CharField(help_text='mashina raqami', max_length=20, verbose_name='Mashina raqami'),
        ),
        migrations.AlterField(
            model_name='oluvchi',
            name='name',
            field=models.CharField(help_text='mashina nomi', max_length=100, verbose_name='Mashina nomi'),
        ),
        migrations.AlterField(
            model_name='oluvchi',
            name='total_cost',
            field=models.FloatField(help_text='umumiy narx', verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='savdo',
            name='amount',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='savdo',
            name='cost',
            field=models.FloatField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='savdo',
            name='oluvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savdolar', to='base.oluvchi', verbose_name='Oluvchi'),
        ),
        migrations.AlterField(
            model_name='savdo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.mahsulot', verbose_name='Mahsulot'),
        ),
    ]
